### ISSUE TITLE
Mashing Causes Crash

### ISSUE THREAD

**Issue by SCAbruh** [DeltaNeverUsed/FishGoBrrr#1]
Clicking at all during a mash zone during the fishing minigame, or failing to catch the fish causes the game to "crash", at least, according to GDWeave.

[GDWeave.log](https://github.com/user-attachments/files/17788513/GDWeave.log)
[Demonstration Clip](https://github.com/user-attachments/assets/b21a3c7c-5b89-40b1-8941-f14f1f530acc)

**Comment by DeltaNeverUsed** [comment]
I'm assuming the game got updated, will fix 👍

**Comment by DeltaNeverUsed** [comment]
Hmm I can't seem to replicate this on my end.

**Comment by DeltaNeverUsed** [comment]
It does look like it's failing to connect to Intiface for you, do you have intiface on a different port from the default?
If so, you'd need to change the url/port in the config file.

It should no longer cause a crash if you update to [1.0.2](https://thunderstore.io/c/webfishing/p/DeltaNeverUsed/FishGoBrrr/versions/)

**Comment by SCAbruh** [comment]
Yea, I should've clarified in the title that it happened without Intiface running. I just wasn't using a device at the moment, and didn't uninstall the mod.
